export const TableData = [
  {
    id: 1,
    first_name: 'Francisco',
    last_name: 'Alessandrini',
    email: 'falessandrini0@live.com',
    gender: 'Male',
    ip_address: '212.78.19.29',
  },
  {
    id: 2,
    first_name: 'Gavra',
    last_name: 'Aspinwall',
    email: 'gaspinwall1@washingtonpost.com',
    gender: 'Female',
    ip_address: '160.43.218.235',
  },
  {
    id: 3,
    first_name: 'Anastasie',
    last_name: 'Ciardo',
    email: 'aciardo2@oakley.com',
    gender: 'Female',
    ip_address: '137.131.224.245',
  },
  {
    id: 4,
    first_name: 'Frederick',
    last_name: 'Whybrow',
    email: 'fwhybrow3@behance.net',
    gender: 'Male',
    ip_address: '167.40.162.218',
  },
  {
    id: 5,
    first_name: 'Lutero',
    last_name: 'Smitten',
    email: 'lsmitten4@spotify.com',
    gender: 'Male',
    ip_address: '12.244.2.5',
  },
  {
    id: 6,
    first_name: 'Sabrina',
    last_name: 'Rowett',
    email: 'srowett5@samsung.com',
    gender: 'Female',
    ip_address: '14.77.254.63',
  },
  {
    id: 7,
    first_name: 'Konstanze',
    last_name: 'Dandie',
    email: 'kdandie6@state.gov',
    gender: 'Female',
    ip_address: '194.130.145.139',
  },
  {
    id: 8,
    first_name: 'Karil',
    last_name: 'Leving',
    email: 'kleving7@facebook.com',
    gender: 'Female',
    ip_address: '98.51.98.185',
  },
  {
    id: 9,
    first_name: 'Tommi',
    last_name: 'Reape',
    email: 'treape8@cbsnews.com',
    gender: 'Female',
    ip_address: '170.45.64.227',
  },
  {
    id: 10,
    first_name: 'Mathew',
    last_name: 'Minear',
    email: 'mminear9@usda.gov',
    gender: 'Male',
    ip_address: '56.18.97.64',
  },
];
